### ISSUE TITLE
Allow specific dimension rtp - Then you will be the best rtp mod

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Picono435/RandomTP#1]
so you want to be the best rtp mod huh? Well then you need to add a per dimension rtp since it has never been done - it would make this the perfect addition to you goal.

/rtpd {AUTOTABDIMID} 

player hits enter ;D

**Comment by Picono435** [comment]
So you want to a person that is in overworld makes the /rtp (id of nether) and teleports to a random location on nether?

**Comment by P3rf3ctXZer0** [comment]
yeah if you want the most options. You could even set so the player has to have been there at least once first :D since the nbt file saves a thing that shows dim ids a player have been.

you could even have something like 
/rtpcd 

which whatever dimension the player could randomly teleport somewhere in current dimension.

also you should have it set so people could disable /rtpd or /rtpcd

Some pack makers may not  want either but me - I would like to /rtpcd more than anything. Also make sure you add a startup cooldown and usage cooldown.

You called your mod the best rtp mod while in its current state it mimics ftbutilities rtp.

**Comment by P3rf3ctXZer0** [comment]
giving you feature ideas that will make your mod stand out.

**Comment by Picono435** [comment]
Well the cooldown is alredy added and your suggestion will be added in the version 1.3! This version will launch at this weekend if everythings goes right.

**Comment by P3rf3ctXZer0** [comment]
stay on 1.12.2 if you want my support - currently thanks to the way forge changed things launchers cannot support forge 1.13.X+ not even twitch ... trust me I check daily if even there partner launcher can.

**Comment by P3rf3ctXZer0** [comment]
https://imgur.com/D9XHL2r.jpg

Also if you look at this LexManos admits a major refractoring. All launchers except vanilla are affected.
https://www.minecraftforge.net/forum/topic/79304-112114-and-lts-system/

**Comment by P3rf3ctXZer0** [comment]
![D9XHL2r](https://user-images.githubusercontent.com/10351221/75581180-a74c1c80-5a2e-11ea-8bdc-efcd804069c7.jpg)

**Comment by Picono435** [comment]
So... that means?

**Comment by Picono435** [comment]
I'm glad to say the the RandomTP 1.3 version is now being worked on! Thank you for your suggestions that if everythings go right will be added.

This issue/suggestion is now closed.
