### ISSUE TITLE
[BUG] /RTP not working. 1.19

### ISSUE THREAD

**Issue by seanimusprime** [Picono435/RandomTP#11]
**Describe the bug**
I tried this mod on 1.18.2 and now on 1.19 and I just cannot get it to work for my server. It's a family SMP, there's only 4 of us and all of us are OP'ed so permissions shouldn't be an issue. When you type /rtp it says it's searching for a safe location but then never teleports us.

**To Reproduce**
1. Type /rtp
2. Wait
3. Nothing happens

**Expected behavior**
To randomly teleport to safe location

**Screenshots**
![image](https://user-images.githubusercontent.com/19805394/172978192-9a2bd700-2bb3-4875-b03c-1d55db93c5b4.png)

**Desktop (please complete the following information):**
 - RandomTP version: randomtp-7.0.0+1.19-fabric.jar
 - Minecraft Version: 1.19
 - Machine Software: Windows 11

**Additional context**
Server console gives this error message after using the command:
```
10.06 02:27:45 [Server] Thread-16/INFO Error executing command.
10.06 02:27:45 [Server] Thread-16/INFO [STDERR]: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because the return value of "com.gmail.picono435.randomtp.api.RandomTPAPI.getBiomeId(net.minecraft.class_1959)" is null
10.06 02:27:45 [Server] Thread-16/INFO [STDERR]: at com.gmail.picono435.randomtp.api.RandomTPAPI.randomTeleport(RandomTPAPI.java:59)
10.06 02:27:45 [Server] Thread-16/INFO [STDERR]: at com.gmail.picono435.randomtp.api.RandomTPAPI.randomTeleport(RandomTPAPI.java:32)
10.06 02:27:45 [Server] Thread-16/INFO [STDERR]: at com.gmail.picono435.randomtp.commands.RTPCommand.lambda$runCommand$4(RTPCommand.java:47)
10.06 02:27:45 [Server] Thread-16/INFO [STDERR]: at java.base/java.lang.Thread.run(Thread.java:831)
```

Here's the list of mods currently on our server:
[Too Fast (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/too-fast)
[Recast (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/recast-fabric)
[Puzzle (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/puzzle)
[Random Shulker Colours (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/random-shulker-colours-fabric)
[Surface Mushrooms (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/surface-mushrooms-fabric)
[LazyDFU (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/lazydfu)
[Random Bone Meal Flowers (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/random-bone-meal-flowers-fabric)
[Carpet TIS Addition (by Fallen_Breath)](https://www.curseforge.com/minecraft/mc-mods/carpet-tis-addition)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[Better Conduit Placement (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/better-conduit-placement-fabric)
[Mooshroom Tweaks (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/mooshroom-tweaks-fabric)
[Mooshroom Spawn (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/mooshroom-spawn-fabric)
[Better Beacon Placement (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/better-beacon-placement-fabric)
[Mineral Chance (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/mineral-chance-fabric)
[Collective (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective-fabric)
[Scaffolding Drops Nearby (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/scaffolding-drops-nearby-fabric)
[Simple Voice Chat (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat)
[FerriteCore (Fabric) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore-fabric)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[No Hostiles Around Campfire (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/no-hostiles-around-campfire-fabric)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Your Options Shall Be Respected (YOSBR) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/yosbr)
[Nether Portal Spread (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/nether-portal-spread-fabric)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Keep My Soil Tilled (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/keep-my-soil-tilled-fabric)
[Lithium (Fabric) (by jellysquid3_)](https://www.curseforge.com/minecraft/mc-mods/lithium)
[Xaero's World Map (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map)
[Fabric Tree Chopper (by magneticflux_)](https://www.curseforge.com/minecraft/mc-mods/fabric-tree-chopper)
[Diggus Maximus (by Kyrptonaught)](https://www.curseforge.com/minecraft/mc-mods/diggus-maximus)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Craft Saddles and Horse Armor (by exlinegames)](https://www.curseforge.com/minecraft/mc-mods/craft-saddles-forge-1-16-5)
[Shulker Drops Two (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/shulker-drops-two-fabric)
[Tax Free Levels (Fabric/Forge) (by Fourmisain)](https://www.curseforge.com/minecraft/mc-mods/tax-free-levels)
[Concrete Conversion (by mrp_v2)](https://www.curseforge.com/minecraft/mc-mods/concrete-conversion)
[Convenient mobGriefing (by Neecko5b84)](https://www.curseforge.com/minecraft/mc-mods/convenient-mobgriefing)
[Smaller Nether Portals (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/smaller-nether-portals-fabric)
[CompleteConfig (by Lortseam_)](https://www.curseforge.com/minecraft/mc-mods/completeconfig)
[Simply Houses (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/simply-houses)
[SilkSpawners (by LordDeatHunter)](https://www.curseforge.com/minecraft/mc-mods/silkspawners)
[Polymer (by Patbox)](https://www.curseforge.com/minecraft/mc-mods/polymer)
[OverpoweredMending (Forge&Fabric) (by RakSrinaNa)](https://www.curseforge.com/minecraft/mc-mods/overpowered-mending)
[Skeleton Horse Spawn (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/skeleton-horse-spawn-fabric)
[Krypton (by tuxed)](https://www.curseforge.com/minecraft/mc-mods/krypton)
[Debugify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/debugify)
[Mod Menu (by ProspectorDev)](https://www.curseforge.com/minecraft/mc-mods/modmenu)
[Healing Campfire (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/healing-campfire-fabric)
[Replanting Crops (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/replanting-crops-fabric)
[Random Sheep Colours (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/random-sheep-colours-fabric)
[Roughly Enough Items Fabric/Forge (REI) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items)
[MemoryLeakFix (by FX_PR0CESS)](https://www.curseforge.com/minecraft/mc-mods/memoryleakfix)
[Not Enough Crashes (Fabric) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes)
[Automatic Doors (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/automatic-doors-fabric)
[Wool Tweaks (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/wool-tweaks-fabric)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Grind Enchantments (by mschae23)](https://www.curseforge.com/minecraft/mc-mods/grind-enchantments)
[Fabric Language Kotlin (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-language-kotlin)
[Starlight (Fabric) (by Spottedstar)](https://www.curseforge.com/minecraft/mc-mods/starlight)
[Furnace Recycle (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/furnace-recycle-fabric)
[Dragon Drops Elytra (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/dragon-drops-elytra-fabric)
[DeepslateCutting (by NoComment1105)](https://www.curseforge.com/minecraft/mc-mods/deepslatecutting)
[Giant Spawn (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/giant-spawn-fabric)
[Alternate Current (by SpaceWalkerRS)](https://www.curseforge.com/minecraft/mc-mods/alternate-current)
[Better Spawner Control (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/better-spawner-control-fabric)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Carpet (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet)
[Zombie Horse Spawn (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/zombie-horse-spawn-fabric)
[Carpet Extra (by gnembon)](https://www.curseforge.com/minecraft/mc-mods/carpet-extra)
[Chunky Pregenerator (Fabric) (by pop4959)](https://www.curseforge.com/minecraft/mc-mods/chunky-pregenerator)
[Name Tag Tweaks (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/name-tag-tweaks-fabric)
[Cloth API (Fabric) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-api)
[Double Doors (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors-fabric)
[Stoneholm, Underground Villages (Fabric) (by TheGrimsey)](https://www.curseforge.com/minecraft/mc-mods/stoneholm)
[Hoe Tweaks (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/hoe-tweaks-fabric)
[Zoomify (by XanderIsDev)](https://www.curseforge.com/minecraft/mc-mods/zoomify)
[Lapis Reserve (by sfort__)](https://www.curseforge.com/minecraft/mc-mods/lapis-reserve)
[Fabric API (by modmuss50)](https://www.curseforge.com/minecraft/mc-mods/fabric-api)
[Smooth Boot (Fabric) (by UltimateBoomer)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot)
[Bigger Sponge Absorption Radius (Fabric) (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/bigger-sponge-absorption-radius-fabric)
[Xaero's Minimap (by xaero96)](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap)
[RandomTP (by Picono435)](https://www.curseforge.com/minecraft/mc-mods/randomtp)

**Comment by Picono435** [comment]
Hello sorry for the inconvenience. If you could please try and check if it still happens with this JAR it would be great.
[randomtp-7.0.0+1.19-fabric.jar.zip](https://github.com/Picono435/RandomTP/files/8877968/randomtp-7.0.0%2B1.19-fabric.jar.zip)

**Comment by joshuacrotts** [comment]
This occurs on 1.18.2 as well. It looks like the `getBiomeId` method is what's causing the problem. That method throws an `AssertionError` exception when called - is this supposed to always be the case, or is there a subclass that I'm not seeing which overrides the method? It also makes me wonder if custom biomes are causing the problem from, for example, Oh The Biomes You Go! which I'm using in my mod pack. Should I also try the version you linked below? @Picono435 

> Hello sorry for the inconvenience. If you could please try and check if it still happens with this JAR it would be great. [randomtp-7.0.0+1.19-fabric.jar.zip](https://github.com/Picono435/RandomTP/files/8877968/randomtp-7.0.0%2B1.19-fabric.jar.zip)

**Comment by PickyPixelStudio** [comment]
Yop,

I've the exact same issue. And i tried :

> Hello sorry for the inconvenience. If you could please try and check if it still happens with this JAR it would be great. [randomtp-7.0.0+1.19-fabric.jar.zip](https://github.com/Picono435/RandomTP/files/8877968/randomtp-7.0.0%2B1.19-fabric.jar.zip)

This time, the console show nothing, but i just get the message in chat, and nothings happen. =/

**Comment by Picono435** [comment]
There is no error in the logs?

**Comment by PickyPixelStudio** [comment]
Nop, nothing in my log...

**Comment by Picono435** [comment]
This issue was fixed in the latest commit.
