### ISSUE TITLE
[SUGGESTION]  Add random spawn

### ISSUE THREAD

**Issue by Zoofule** [Picono435/RandomTP#12]
**Is your feature request related to a problem? Please describe.**
Having to have everyone on the server start at the same location is frustrating when I want people to spread out.

**Describe the solution you'd like**
Add a config option that makes a person spawn in a random location the first time that player joins the world.

**Describe alternatives you've considered**
N/A

**Additional context**
Possibly add an option to set how close people can spawn and how far apart they can spawn.

**Comment by Picono435** [comment]
This feature has been added thank you for your suggestion.
