### ISSUE TITLE
Error Executing Command

### ISSUE THREAD

**Issue by Coolkc456** [Picono435/RandomTP#14]
I'm receiving errors in the console when /rtp is executed. I don't get teleported, and all I'm told in chat is "Finding a safe random teleport location..."
Log: https://pastebin.com/KPJX7Sky
 - RandomTP version: 6.1.0
 - Minecraft Version: 1.18.2

**Comment by dangerousnick** [comment]
Same I was using the version for 1.16 though

**Comment by Picono435** [comment]
Does it happen only in Mohist/Magma servers?

**Comment by dangerousnick** [comment]
Not sure I was using archlight

**Comment by Picono435** [comment]
Yeah, I meant hybrid servers so including archlight. I can try to fix it but no promises.

**Comment by Picono435** [comment]
This issue should be resolved in the lastest releases, thank you for reporting it.
