### ISSUE TITLE
[SUGGESTION] Slow-search mode

### ISSUE THREAD

**Issue by DatCaptainHorse** [Picono435/RandomTP#17]
**Is your feature request related to a problem? Please describe.**
Using the rtp command most of the time causes server to timeout and crash. TBH it's only a 4-core Xeon but it's enough for me and few friends.

**Describe the solution you'd like**
Config boolean for a "slow-mode" search for rtp, which would slow down the search process for teleport but allow the server to keep functioning until one is found.

**Describe alternatives you've considered**
I've tried other rtp command providing mod I could find, unfortunately it also has same issue and didn't support other dimensions.

**Additional context**
3 cores of the 4-core Xeon given to server, just so it doesn't totally freeze everything. 6GB of RAM allocated.

**Comment by Picono435** [comment]
What minecraft version are you using?

**Comment by DatCaptainHorse** [comment]
Version is 1.19.2, I just noticed the 1.19.3 version probably has the fixes implemented for this issue.

Can be closed if no more info is needed, still waiting on other mods to update before being able to use 1.19.3.

**Comment by Picono435** [comment]
You can try and use the 1.19.3 version in 1.19.2 but not sure if it would work.
