### ISSUE TITLE
[BUG] Empty config file, timeouts and watchdogs

### ISSUE THREAD

**Issue by trevorjd** [Picono435/RandomTP#20]
**Describe the bug**
1. The config.yml created by both randomtp-7.2.0+1.19-fabric.jar and randomtp-7.1.0+1.19-fabric.jar is empty.
2. When I use the /rtp command, usually the client times out or the server watchdog detects a 60s tick and restarts.

**To Reproduce**
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
For the executing player to be teleported without disconnecting or crashing the server.

**Screenshots**

**Desktop (please complete the following information):**
 - RandomTP version: 7.1.0
 - Minecraft Version: 1.19.2
 - Machine Software: Windows

**Additional context**
Hi,

I've added RandomTP to "Another Quality Modpack 2" MC 1.19.2 - Fabric

Initially had v7.2.0 installed. Did an /rtp. After a long while wondering if anything was happening, my client disconnected then a minute later, the server watchdog crashed due to a 60+ second tick.  Fired the server back up and found the randomTP had worked, as my toon was now at 3277374, 109, -28111481!

Went to look for the config and found the config.yml was empty.  A little snooping around and I found a recommendation to use v7.1.0 for 1.19.2.  Deleted the config and installed 7.1.0.  The new config.yml is still empty.

Logged in again, /rtp worked and sent me to -25712981, 69, -19185569. 
Explored a little. /rtp again and lost connection after a short while.  Server is still running.

I did not get a "Finding a safe location..." message when I ran /rtp
I did get a "You have been teleported to..." message after the successful teleport

I located and pasted in the contents of https://github.com/Picono435/RandomTP/blob/1.19.3/common/src/main/resources/config.yml 
Disabled rtpd and rtpb and set a max range of 10000
Fired the server back up, logged in ran /rtp 
This time I did get a "finding a safe location..." message but the server crashed with a 60s tick.

So... any ideas? :)

**Comment by Picono435** [comment]
That issue was identified and was fixed in version 7.2.0 to Minecraft 1.19.3... Unfortunately, if you want to keep the version you are working with right now you will have to manually copy the file https://github.com/Picono435/RandomTP/blob/7.1.0%2B1.19/common/src/main/resources/config.yml into config.yml and https://github.com/Picono435/RandomTP/blob/7.1.0%2B1.19/common/src/main/resources/messages.yml into messages.yml.

If this does not work please send me the logs file so I can help you.

**Comment by trevorjd** [comment]
Thanks. Seems to be working reliably. Timed me out once but worked just fine for 7 or 8 tries after that.
