### ISSUE TITLE
[BUG] crash report

### ISSUE THREAD

**Issue by kuba26038** [Picono435/RandomTP#21]
**Describe the bug**
the game crashes whenever i try to join a world while having this mod
**To Reproduce**
launch minecraft, join a world, crash

**Expected behavior**
the game shouldn't crash

**Screenshots**

**Desktop (please complete the following information):**
 - RandomTP version: randomtp-7.2.0+1.19-forge
 - Minecraft Version: 1.19.2
 - Machine Software [e.g. Linux, Windows, MACOSX... (NOT REQUIRED]

**Additional context**

[crash-2023-02-10_20.35.57-client.txt](https://github.com/Picono435/RandomTP/files/10710641/crash-2023-02-10_20.35.57-client.txt)

**Comment by kuba26038** [comment]
just tested and it seems to be an incompatibility between this mod and blueprint by abnormals, please fix

**Comment by Picono435** [comment]
If you are using Minecraft 1.19.2 you need to rollback to the previous RandomTP version.

**Comment by kuba26038** [comment]
if the 1.19.3 version doesn't work with 1.19.2, maybe it shouldn't be tagged as 1.19.2 compatible? seems like an easily fixable issue to me
