### ISSUE TITLE
[BUG] Time Out message doesn't send

### ISSUE THREAD

**Issue by ItsaGlitch1** [Picono435/RandomTP#23]
**Describe the bug**
When putting a limited amount of tries, if RandomTP runs out of tries for the command, the server doesn't send the timed out message to the player.

**To Reproduce**
1. set max tries to a limited number (ex: 5)
2. save config and restart server to reload the config
3. run /rtp

**Expected behavior**
"Timed out trying to find a safe location to warp to."

**Desktop (please complete the following information):**
 - RandomTP version: 7.1.0
 - Minecraft Version: 1.19.2

**Additional context**
If you do get teleported, try again until you won't be teleported.

**Comment by Picono435** [comment]
This should be fixed in the latest release. If not make sure to re-open the issue or create a new one.
