### ISSUE TITLE
1.19.4 Native Support [SUGGESTION] 

### ISSUE THREAD

**Issue by KhaozFrost** [Picono435/RandomTP#27]
**Is your feature request related to a problem? Please describe.**
1.19.4 Native Support 
**Describe the solution you'd like**
1.19.4 Native Support 
**Describe alternatives you've considered**

**Additional context**

**Comment by Picono435** [comment]
Hi! Could you specify any reason to follow this huge change?

**Comment by KhaozFrost** [comment]
Cobblemon will be moving to 1.19.4 in its next update and alot of fabric based servers use this mod. I'm just trying to prepare my servers for that change and try to get everything that I don't have at 1.19.4 ready so that nothing ends up breaking. I was also wondering if its possible to add permissions onto stuff like dimension restrictions via perm node etc.

**Comment by Picono435** [comment]
There is a way to add permissions check in the change log. Also, I will make sure to upgrade to 1.19.4 very soon. Sorry, I thought we were talking about another project.
