### ISSUE TITLE
[BUG] permissions don't work

### ISSUE THREAD

**Issue by Lezers** [Picono435/RandomTP#29]
**Describe the bug**

I'm configuring the permissions in luckyperms and I also tried in ftbranks, but I keep saying that it doesn't have permission

**Expected behavior**

I expected that the player that is in the default rank could use /rtp after I set the permissions

**Screenshots**

https://prnt.sc/9hn-gbt8zfKO

**Desktop (please complete the following information):**
 - RandomTP version: [6.3.0]
 - Minecraft Version: [1.18.2]
 - Machine Software [Windows]

**Comment by Picono435** [comment]
This should be fixed in the latest release. If not make sure to re-open the issue or create a new one.
