### ISSUE TITLE
[BUG] Rtp never teleports in negative coordinates 

### ISSUE THREAD

**Issue by jinkhya** [Picono435/RandomTP#3]
**Describe the bug**
Rtp never teleports in negative coordinates

**To Reproduce**
1. add RandomTP to an instance and load a world
2. run /rtp

**Expected behavior**
To randomize either positive or negative coordinates.

**Desktop (please complete the following information):**
 - RandomTP version: 1.3
 - Minecraft Version: 1.16.5
 - Machine Software Linux

**Comment by Picono435** [comment]
This issue was identified and is now being fixed. We are sorry for the inconvenience.

**Comment by jinkhya** [comment]
Awesome! thanks !

**Comment by Picono435** [comment]
A fix for this issue was implemented and it will be fixed in next update with a lot of other fixes. Thank you for reporting it.

**Comment by jinkhya** [comment]
Cheers, keep the good work !

**Comment by Picono435** [comment]
This issue was fixed in the latest version. Please be sure to update your mod, if the issue persists make sure to re-create this issue.
