### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AlexMarvel** [Picono435/RandomTP#32]
*![image](https://github.com/Picono435/RandomTP/assets/25487961/21b752c1-3cf1-4e95-97ac-6928899b7162)

**Comment by Picono435** [comment]
Please provide with all the details that are asked when you create an issue.

**Comment by AlexMarvel** [comment]
what information do you provide?

**Comment by Picono435** [comment]
If you still have this issue please provide with your configuration files.
