### ISSUE TITLE
[SUGGESTION] Teleport to a specific biome

### ISSUE THREAD

**Issue by GamerPi** [Picono435/RandomTP#5]
Hello, I would love if this mod had some way to rtp in a specific Biome. A good command could be /be to or /biomertp

**Comment by Picono435** [comment]
Hello, I really appreciate your suggestion and I will make sure to make a look at it. I can say that this will probably be added in a future update.

**Comment by GamerPi** [comment]
Just curious if there was any progress on this :) Have a good day!

**Comment by Picono435** [comment]
Hello yes but currently I am working on updating all the projects to 1.17/Java 16 so it will probably take a while.

**Comment by Picono435** [comment]
I can confirm this feature will be added in a future update, there is no ETA for it to be released yet but I hope I can add it asap.

**Comment by Picono435** [comment]
This suggestion has been added and has been available for a long time now...
